from tkinter import *
root = Tk()
def msg1():
    print('clicked New Project')
def msg2():
    print('clicked Undo')
def msg3():
    print('clicked Tool Windows')
def msg4():
    print('clicked Back')
def msg5():
    print('clicked Override Methods')
main_menu = Menu(root)
root.config(menu=main_menu)
sub_menu1 = Menu(main_menu)
main_menu.add_cascade(label='File', menu=sub_menu1)
sub_menu1.add_command(label='New Project', command=msg1)
sub_menu1.add_command(label='New')
sub_menu1.add_separator()
sub_menu1.add_command(label='Open')
sub_menu1.add_command(label='Save As')
sub_menu1.add_separator()
sub_menu1.add_command(label='Open Recent')
sub_menu1.add_command(label='Close Projects in Current Window')
sub_menu1.add_separator()
sub_menu1.add_command(label='Exit', command=root.quit)


sub_menu2 = Menu(main_menu)
main_menu.add_cascade(label='Edit', menu=sub_menu2)
sub_menu2.add_command(label='Undo', command=msg2)
sub_menu2.add_command(label='Redo')
sub_menu2.add_separator()
sub_menu2.add_command(label='Cut')
sub_menu2.add_command(label='Copy')
sub_menu2.add_separator()
sub_menu2.add_command(label='Copy Path or Reference')
sub_menu2.add_command(label='Paste')

sub_menu3 = Menu(main_menu)
main_menu.add_cascade(label='View', menu=sub_menu3)
sub_menu3.add_command(label='Tool Windows', command=msg3)
sub_menu3.add_command(label='Appearance')
sub_menu3.add_separator()
sub_menu3.add_command(label='Quick Definition')
sub_menu3.add_command(label='Quick Type Definition')
sub_menu3.add_separator()
sub_menu3.add_command(label='Parameter Info')
sub_menu3.add_command(label='Type Info')

sub_menu4 = Menu(main_menu)
main_menu.add_cascade(label='Navigate', menu=sub_menu4)
sub_menu4.add_command(label='Back', command=msg4)
sub_menu4.add_command(label='Forward')
sub_menu4.add_separator()
sub_menu4.add_command(label='Search Everywhere')
sub_menu4.add_command(label='Class')
sub_menu4.add_separator()
sub_menu4.add_command(label='File')
sub_menu4.add_command(label='Symbol')

sub_menu5 = Menu(main_menu)
main_menu.add_cascade(label='Code', menu=sub_menu5)
sub_menu5.add_command(label='Override Methods', command=msg5)
sub_menu5.add_command(label='Implement Methods')
sub_menu5.add_separator()
sub_menu5.add_command(label='Generate')
sub_menu5.add_command(label='Inspect Code')
sub_menu5.add_separator()
sub_menu5.add_command(label='Code Cleanup')
sub_menu5.add_command(label='Analyze Code')

root.mainloop()